# -----------------------------------------------------------------------------
# Makefile for the C99 Compiler
# -----------------------------------------------------------------------------

# --- Compiler and Tool Definitions ---
# Use 'gcc' as the C compiler.
# Use 'bison' and 'flex' for parser and lexer generation.
CC = gcc
YACC = bison
LEX = flex

# --- Flags ---
# CFLAGS: Flags for the C compiler.
#   -g: Include debugging information.
#   -Wall: Enable all common warnings.
#   -I.: Add the current directory to the include path (so files can find .h files).
CFLAGS = -g -Wall -I.

# LDFLAGS: Flags for the linker.
#   -lm: Link the math library (needed for functions like atof).
LDFLAGS = -lm

# --- File Definitions ---
# TARGET: The name of the final executable file.
TARGET = c99_compiler

# SOURCES: Your handwritten C source files.
SOURCES = \
    symbol_table.c \
    semantics.c \
    ir_generator.c

# GEN_SOURCES: C source files that will be generated by Bison and Flex.
GEN_SOURCES = \
    parser.tab.c \
    lex.yy.c

# OBJECTS: The list of object files (.o) to be created.
# This is automatically generated by replacing the .c extension with .o for all sources.
OBJECTS = $(SOURCES:.c=.o) $(GEN_SOURCES:.c=.o)

# GEN_HEADER: The header file generated by Bison.
GEN_HEADER = parser.tab.h

# --- Build Rules ---

# The default rule, executed when you just run 'make'.
# It depends on the final executable.
all: $(TARGET)

# Rule to create the final executable (linking step).
# This rule depends on all the object files.
# It links them together using the C compiler.
$(TARGET): $(OBJECTS)
	@echo "==> Linking executable: $@"
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJECTS) $(LDFLAGS)

# Rule to generate the parser C file and header file from the parser.y source.
# The '-d' flag tells Bison to create the header file.
# The '-v' flag creates a verbose report file (parser.output), which is useful for debugging the grammar.
$(GEN_HEADER) parser.tab.c: parser.y
	@echo "==> Generating parser from parser.y"
	$(YACC) -d -v parser.y

# Rule to generate the lexer C file from lexer.l.
# This depends on the header from Bison because the lexer needs the token definitions.
lex.yy.c: lexer.l $(GEN_HEADER)
	@echo "==> Generating lexer from lexer.l"
	$(LEX) -o lex.yy.c lexer.l

# Generic rule for compiling a .c file into a .o file.
# '$<' is an automatic variable that means the first prerequisite (the .c file).
# '$@' is an automatic variable that means the target of the rule (the .o file).
%.o: %.c
	@echo "==> Compiling C source: $<"
	$(CC) $(CFLAGS) -c -o $@ $<

# --- Cleanup Rule ---

# The 'clean' rule is used to remove all generated files.
# This allows you to start a fresh build.
clean:
	@echo "==> Cleaning up generated files"
	rm -f $(TARGET) $(OBJECTS) $(GEN_SOURCES) $(GEN_HEADER) parser.output lex.backup

.PHONY: all clean

